### PR TITLE
Update to WPCS v3

### PR DESCRIPTION
**Pull request by danielbachhuber**
See https://github.com/wp-cli/wp-cli-tests/issues/175

### CODE REVIEW

**Comment by swissspidy** [comment]
Is this even used here? 🤔

**Comment by danielbachhuber** [comment]
> Is this even used here? 🤔

@swissspidy Assuming yes because this is the automated tests repo, but let's see 10df2718

**Comment by wojsmol** [comment]
Yes, because [this](https://github.com/wp-cli/automated-tests/blob/eb9566e811d2b3c4d5bd8270f260f6ad41240671/composer.json#L31-L39) command are defined in `wp-cli-test` package

**Comment by danielbachhuber** [comment]
Definitely yes 😁

**Comment by swissspidy** [comment]
Ah I see, it's needed for setting up the database etc. But not for PHPCS, as there aren't really any PHP files.

**Review by swissspidy — APPROVED** [review]

**Pull request merged**
