### PR TITLE
Extend test script for phar distributions.

### PR DESCRIPTION
**Pull request by schlessera**
The test script can now test against both source packages as well as phar
releases.

To test against a Phar release, add the `TEST_PHAR` environment variable.
Possible values:
* `all`
* `stable`
* `nightly`
* `none`

See #4108

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@schlessera Looks like the build still fails?

**Comment by schlessera** [comment]
@danielbachhuber Yes, and these failures probably point to problems in the interaction between the Phar code and the source tests.

I think I need to fetch the exact tag that the Phar was build with, but not sure I can do that reliably. Probably, latest released tag is the best I can manage.

**Comment by gitlost** [comment]
I think the only problem here is you've forgotten about the ancient `composer.lock`  - remove that and things should work.

(Which suggests a way to do the stable build maybe - have a `composer.lock.stable` and use that when testing stable.)

**Comment by schlessera** [comment]
Thanks, @gitlost ! I feel really stupid now...

I thought about all sorts of combinations between the Phar, the framework and the commands... and never considered this package itself! -.-

**Pull request merged**
