### PR TITLE
Looking for the root of test failures

### PR DESCRIPTION
**Pull request by szepeviktor**
remove `--format progress`

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@szepeviktor Keep in mind: these builds take _hours_ to run. Best to keep the testing process as minimal as possible.

**Comment by szepeviktor** [comment]
Travis log need to be downloaded and: `less -R log.txt`

**Comment by szepeviktor** [comment]
I think tilde make it fail

```
2.26s$ ./ci/test.sh

Running source package tests...

Testing package wp-cli/wp-cli...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

Testing package wp-cli/cache-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

Testing package wp-cli/checksum-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

Testing package wp-cli/config-command...

DBG:__vendor/bin/behat --format progress --tags=~@require-php-7.0&&~@github-api&&~@broken --strict 

Testing package wp-cli/core-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

Testing package wp-cli/cron-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

Testing package wp-cli/db-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

Testing package wp-cli/entity-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

Testing package wp-cli/eval-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

Testing package wp-cli/export-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

Testing package wp-cli/extension-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

Testing package wp-cli/import-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

Testing package wp-cli/language-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

Testing package wp-cli/media-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken&&~@require-extension-imagick --strict 

Testing package wp-cli/package-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

Testing package wp-cli/rewrite-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

Testing package wp-cli/role-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

Testing package wp-cli/scaffold-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

Testing package wp-cli/search-replace-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

Testing package wp-cli/server-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

Testing package wp-cli/shell-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

Testing package wp-cli/super-admin-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

Testing package wp-cli/widget-command...

DBG:__vendor/bin/behat --format progress --tags=~@github-api&&~@broken --strict 

All Packages were successfully tested.
```

**Comment by szepeviktor** [comment]
Declare defeat.

Look like Symfony\Console forgets about registered helpers (`progress`)

**Comment by danielbachhuber** [comment]
> Declare defeat.

No worries, thanks for your attempt.

> Looks like Symfony\Console forgets about registered helpers

Huh. I'm totally confused as to why it works for some tests but fails for others.

**Pull request closed without merging**
